configuration:
  - Debug
  - Release

environment:
  matrix:
    - generator: "Visual Studio 14 2015"
    - generator: "Visual Studio 14 2015 Win64"
    - generator: "Visual Studio 10 2010"
    - generator: "Visual Studio 10 2010 Win64"

matrix:
  fast_finish: true
  
shallow_clone: true

before_build:
  - cmake . -Bbuild -G"%generator%"

build_script:
  - set CMAKE_BUILD_FLAGS=--config %configuration% -- /m /v:m
  - cmake --build build %CMAKE_BUILD_FLAGS%